language: cpp

dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-9
            - libboost-system-dev
            - librange-v3-dev
            - libeigen3-dev
            - libarmadillo-dev
      env:
        - MATRIX_EVAL="CXX=clang++-9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-system-dev
            - librange-v3-dev
            - libeigen3-dev
            - libarmadillo-dev
      env:
        - MATRIX_EVAL="CXX=g++-8"

before_script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX ..
  - thread_count=`cat /proc/cpuinfo | grep "processor" | wc -l`
  - echo The thread count is $thread_count.

script:
  - make -j$thread_count
